name: Mocaverse Realm Tickets Selection Round 2
on:
  workflow_dispatch:
  push:
    branches: round2

jobs:
  selection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: round2

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run selection
        run: python3 selection.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Round 2 Selection Winners